version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/java"
    schedule:
      interval: "weekly"
      day: "tuesday"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
  - package-ecosystem: "npm"
    directory: "/nodejs/wrapper-adot"
    schedule:
      interval: "weekly"
      day: "tuesday"
    rebase-strategy: "auto"
