version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: sunday
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: '/'
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "npm dependencies"
    rebase-strategy: "auto"
