receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:55680
  otlp/2:
    protocols:
      grpc:
        endpoint: localhost:55681

exporters:
  awsxray:
  awsemf:
  otlphttp:
    endpoint: "http://localhost:55681"
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
    traces/2:
      receivers: [otlp/2]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      exporters: [awsemf]
