receivers:
  otlp:
    protocols:
      grpc:

exporters:
  awsemf:
  logging:
    loglevel: debug
  otlphttp:
    endpoint: "http://44.234.62.36:55681"
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp, logging]
    metrics:
      receivers: [otlp]
      exporters: [awsemf]

