receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680
  otlp/2:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55681

exporters:
  awsxray:
  awsemf:
  otlp:
    endpoint: 0.0.0.0:55681
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    traces/2:
      receivers: [otlp/2]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      exporters: [awsemf]
