#!/bin/bash

export NODE_OPTIONS="--require /opt/adot-extension.js ${NODE_OPTIONS}"

# If both OTEL_NODE_ENABLED_INSTRUMENTATIONS and OTEL_NODE_DISABLED_INSTRUMENTATIONS are not configured,
# set OTEL_NODE_ENABLED_INSTRUMENTATIONS="aws-sdk,aws-lambda,http"
if [ -z "${OTEL_NODE_ENABLED_INSTRUMENTATIONS}" ] && [ -z "${OTEL_NODE_DISABLED_INSTRUMENTATIONS}" ]; then
    export OTEL_NODE_ENABLED_INSTRUMENTATIONS="aws-sdk,aws-lambda,http"

# Else if OTEL_NODE_ENABLED_INSTRUMENTATIONS is configured and OTEL_NODE_DISABLED_INSTRUMENTATIONS is not,
# append OTEL_NODE_ENABLED_INSTRUMENTATIONS with "aws-lambda,http"
elif [ -n "${OTEL_NODE_ENABLED_INSTRUMENTATIONS}" ] && [ -z "${OTEL_NODE_DISABLED_INSTRUMENTATIONS}" ]; then
    export OTEL_NODE_ENABLED_INSTRUMENTATIONS="${OTEL_NODE_ENABLED_INSTRUMENTATIONS},aws-lambda,http"

# Else if both OTEL_NODE_ENABLED_INSTRUMENTATIONS and OTEL_NODE_DISABLED_INSTRUMENTATIONS are configured,
# append OTEL_NODE_ENABLED_INSTRUMENTATIONS with "aws-lambda,http"
elif [ -n "${OTEL_NODE_ENABLED_INSTRUMENTATIONS}" ] && [ -n "${OTEL_NODE_DISABLED_INSTRUMENTATIONS}" ]; then
    export OTEL_NODE_ENABLED_INSTRUMENTATIONS="${OTEL_NODE_ENABLED_INSTRUMENTATIONS},aws-lambda,http"

# Else do nothing
fi

if [[ -z "$OTEL_PROPAGATORS" ]]; then
  export OTEL_PROPAGATORS="tracecontext,baggage,xray-lambda"
fi

source /opt/otel-handler-upstream
