AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  AwsObservability:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aws-distro-for-opentelemetry-python-38-preview
      Description: AWS Distro for Opentelemetry Python38
      ContentUri: ./aws_observability
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: makefile
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AWS-Distro-for-OpenTelemetry-Python-38
    Description: AWS Distro for Opentelemetry Python38
    Author: aws-observability
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['opentelemetry', 'python38', 'layer']
    HomePageUrl: https://aws.amazon.com/products/management-and-governance/use-cases/monitoring-and-observability/
    SemanticVersion: 0.1.0
    SourceCodeUrl: https://github.com/aws-observability/aws-otel-lambda/sample-apps/python-lambda