AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      TracingEnabled: true
      OpenApiVersion: 3.0.2
  function:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Description: Build AWS Observability layer
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - CloudWatchAgentServerPolicy
      ReservedConcurrentExecutions: 1
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref api
            Path: /
            Method: GET
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AWS-Distro-for-OpenTelemetry-Java-Sample
    Description: AWS Distro for Opentelemetry Java Sample
    Author: aws-observability
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['opentelemetry', 'java', 'sample']
    HomePageUrl: https://aws.amazon.com/products/management-and-governance/use-cases/monitoring-and-observability/
    SemanticVersion: 0.1.0
    SourceCodeUrl: https://github.com/aws-observability/aws-otel-lambda/sample-apps/java-lambda