name: CleanResources

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Clean resources'
        required: false
        default: 'Python3.8'
      target:
        description: 'stacks to be deleted'
        required: true
        default: 'cd-aot*'

jobs:
  clean-resources:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{matrix.region}}
      WORK_DIR: "sample-apps/python-lambda"

    strategy:
      matrix:
        region: [us-west-2, us-east-2, eu-west-1, eu-west-2]
    steps:
      - uses: actions/checkout@v2

      - name: init
        run: |
          chmod -R +x sample-apps/python-lambda/tools
          cp sample-apps/python-lambda/tools/* .
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_2 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_2 }}
          mask-aws-account-id: false
          aws-region: ${{matrix.region}}

      - name: clean stacks
        run: |
          echo ${{ github.event.inputs.target }}
          ./cleanStacks.sh ${{ github.event.inputs.target }}

