name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  tox:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python: [3.8]
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run tox
        run: |
          echo tox...
          cd sample-apps/python-lambda && tox

  build:
    needs: tox
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{matrix.region}}
      WORK_DIR: "sample-apps/python-lambda"
    
    strategy:
      matrix:
        region: [us-west-1]

    steps:
      - uses: actions/checkout@v2
          
      - name: init
        run: |
          echo $AWS_REGION
          cd $WORK_DIR
          chmod -R +x tools
          cp tools/* .
      
      - name: build
        run: |
          cd $WORK_DIR
          chmod +x run.sh
          ./run.sh -b
